version: '3.9'

services:
  confluence:
    build: .
    image: example.com/confluence:8.0.3
    container_name: confluence
    restart: unless-stopped
    environment:
      - TZ=Asia/Tehran
    ports:
      - 8080:8090
    volumes:
      - conf:/var/atlassian/application-data/confluence
  
  jira:
    build: .
    image: example.com/jira-software:9.12.5
    container_name: jira
    restart: unless-stopped
    environment:
      - TZ=Asia/Tehran
    ports:
      - 8081:8080
    volumes:
      - jira:/var/atlassian/application-data/jira
  
  postgres:
    image: postgres:15.1
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_DB=confluence
    ports:
      - 5432:5432
    volumes:
      - pgsql:/var/lib/postgresql/data

volumes:
  conf:
  jira:
  pgsql:
