FROM atlassian/jira-software:9.12.5
USER root 
 # Add proxy unpacking to container 
COPY atlassian-agent-use-in-JAVA_OPTS.jar /opt/atlassian/jira/ 
 # Set Startup Loading Agent Package
RUN echo "export CATALINA_OPTS=\"-javaagent:/opt/atlassian/jira/atlassian-agent-use-in-JAVA_OPTS.jar \${CATALINA_OPTS}\"" >> /opt/atlassian/jira/bin/setenv.sh
