version: '3'

tasks:
  build:
    cmds:
      - docker build -t example.com/confluence:8.0.3 -f Dockerfile .
  
  push:
    cmds:
      - docker push example.com/confluence:8.0.3
  
  gen:
    cmds:
      - java -jar atlassian-agent-license-generator.jar -d -m test@gmail.com -n BAT -p conf -o http://localhost -s {{.CLI_ARGS}}
  
  plugin:
    cmds:
      - java -jar atlassian-agent-license-generator.jar -d -m test@gmail.com -n BAT -p {{.CLI_ARGS}} -o http://localhost -s {{.CLI_ARGS}}
  
  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down

  buildjira:
    cmds:
      - docker build -t example.com/jira-software:9.12.5 -f Dockerfile-jira .
  
  pushjira:
    cmds:
      - docker push example.com/jira-software:9.12.5
  
  genjira:
    cmds:
      - java -jar atlassian-agent-license-generator.jar -d -m test@gmail.com -n BAT -p jira -o http://localhost -s {{.CLI_ARGS}}
  
